package checks

import (
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"regexp"
	"runtime"
	"strings"
)

// linuxCrossTarget is the Linux triple we type-check against from a non-Linux host.
const linuxCrossTarget = "x86_64-unknown-linux-gnu"

// zigTarget is how zig spells the same thing. Zig has no vendor field, and it rejects the Rust
// triple outright ("unable to parse target query: UnknownOperatingSystem").
const zigTarget = "x86_64-linux-gnu"

// RunLinuxCross type-checks and lints the desktop app for Linux from a non-Linux host.
//
// Marked slow in the registry, so it stays out of a plain `./scripts/check.sh` run: it needs
// zig, whose first install is a few hundred megabytes. Setup and background: see the
// cross-compilation section in `AGENTS.md`.
func RunLinuxCross(ctx *CheckContext) (CheckResult, error) {
	if runtime.GOOS == "linux" {
		return Skipped("already on Linux; the clippy check covers this target"), nil
	}
	if runtime.GOOS == "windows" {
		return Skipped("the zig wrapper this needs is a POSIX shell script"), nil
	}

	rustDir := filepath.Join(ctx.RootDir, "apps", "desktop")
	if _, err := os.Stat(filepath.Join(rustDir, "Cargo.toml")); os.IsNotExist(err) {
		return Skipped("apps/desktop/Cargo.toml not found"), nil
	}

	if err := requireRustupTarget(linuxCrossTarget); err != nil {
		return CheckResult{}, err
	}
	shimDir, err := ensureZigShims(ctx.RootDir)
	if err != nil {
		return CheckResult{}, err
	}

	cmd := exec.Command("cargo", "clippy", "--workspace", "--target", linuxCrossTarget, "--all-targets", "--", "-D", "warnings")
	cmd.Dir = rustDir
	// cc-rs reads the triple with underscores; the linker variable is Cargo's own spelling.
	// `zstd-sys` is the only C in the Linux graph, and these are what let it build.
	cc := filepath.Join(shimDir, "linux-cc")
	cmd.Env = append(os.Environ(),
		"CC_x86_64_unknown_linux_gnu="+cc,
		"AR_x86_64_unknown_linux_gnu="+filepath.Join(shimDir, "linux-ar"),
		"CARGO_TARGET_X86_64_UNKNOWN_LINUX_GNU_LINKER="+cc,
	)
	output, err := RunCommand(cmd, true)
	if err != nil {
		return CheckResult{}, fmt.Errorf("cross-check for "+linuxCrossTarget+" failed\n%s", indentOutput(stripBuildScriptEcho(output)))
	}

	count := len(regexp.MustCompile(`(?m)^\s*Checking`).FindAllString(output, -1))
	if count == 0 {
		return Success(linuxCrossTarget + ": no warnings"), nil
	}
	result := Success(fmt.Sprintf("%s: %d %s checked, no warnings", linuxCrossTarget, count, Pluralize(count, "crate", "crates")))
	result.Total = count
	return result, nil
}

// zigShims is the pair of wrappers cc-rs drives, rendered with zig's absolute path.
//
// The `--target=` strip is the whole reason a wrapper exists: cc-rs passes the Rust triple,
// which zig can't parse, so we drop that argument and hand zig its own spelling. The loop
// rotates the argument list rather than building a string, so paths with spaces survive.
var zigShims = map[string]string{
	"linux-cc": `#!/bin/sh
# Generated by scripts/check/checks/desktop-rust-linux-cross.go. Edits get overwritten.
n=$#
i=0
while [ "$i" -lt "$n" ]; do
  arg=$1
  shift
  case "$arg" in
    --target=*) ;;
    *) set -- "$@" "$arg" ;;
  esac
  i=$((i + 1))
done
exec %s cc -target ` + zigTarget + ` "$@"
`,
	"linux-ar": `#!/bin/sh
# Generated by scripts/check/checks/desktop-rust-linux-cross.go. Edits get overwritten.
exec %s ar "$@"
`,
}

// ensureZigShims returns a directory holding a `cc` and an `ar` that produce Linux objects, and
// writes them if needed.
//
// Apple's command line tools cross-compile to nothing, so the C in `zstd-sys` needs a real Linux
// toolchain. zig ships one for every target it supports, in a single self-contained download, and
// it's already a mise-managed tool here.
func ensureZigShims(rootDir string) (string, error) {
	zig, err := findZig()
	if err != nil {
		return "", err
	}

	shimDir := filepath.Join(rootDir, "target", "cross-check-bin")
	if err := os.MkdirAll(shimDir, 0755); err != nil {
		return "", fmt.Errorf("couldn't create %s: %w", shimDir, err)
	}
	for name, template := range zigShims {
		path := filepath.Join(shimDir, name)
		want := fmt.Sprintf(template, zig)
		// Rewrite whenever zig moves, which a mise upgrade does.
		if existing, err := os.ReadFile(path); err == nil && string(existing) == want {
			continue
		}
		if err := os.WriteFile(path, []byte(want), 0755); err != nil {
			return "", fmt.Errorf("couldn't write %s: %w", path, err)
		}
	}
	return shimDir, nil
}

// findZig returns an absolute path to a working zig.
//
// It prefers whatever is on `PATH`, then asks mise. The mise fallback matters because zig is
// deliberately absent from `.mise.toml`: pinning it there would make all five CI jobs download it
// for a check that only ever runs on a developer's Mac.
func findZig() (string, error) {
	if path, err := exec.LookPath("zig"); err == nil {
		if _, err := RunCommand(exec.Command(path, "version"), true); err == nil {
			return path, nil
		}
	}
	if CommandExists("mise") {
		// `mise where` answers without the tool being active in this directory, unlike
		// `mise which`. It prints nothing and exits non-zero when zig isn't installed.
		out, err := RunCommand(exec.Command("mise", "where", "zig"), true)
		if err == nil {
			zig := filepath.Join(strings.TrimSpace(out), "zig")
			if _, err := os.Stat(zig); err == nil {
				return zig, nil
			}
		}
	}
	return "", fmt.Errorf("zig is missing, install it with:\n      mise install zig@latest")
}
