//! Render `settings::windows::file_types` into the NSIS include the Windows installer compiles.
//!
//! The installer needs the same registry writes the app's "Register Prvw's file types" button
//! makes, and NSIS can't link a Rust crate to ask. So this renders them, the check runner
//! compares the result with the committed `.nsh`, and the two can't drift.
//!
//! ## NSIS quoting, which is the only fiddly part
//!
//! NSIS delimits strings with `"`, `'`, or a backtick, and whichever one opens the string is the
//! only one that closes it; the other two are ordinary characters. So [`nsis_string`] picks a
//! delimiter the value doesn't contain rather than escaping quotes. `$` is NSIS's escape
//! character in every one of those forms and has to be doubled, which is why the executable's
//! path travels through here as [`EXE_PLACEHOLDER`] and only becomes `$INSTDIR\prvw.exe` after
//! the escaping is done.

use crate::file_types::{self, RegistryRemoval, RegistryValue};
use std::path::Path;

/// What `file_types::registration` is handed in place of a real install path. It survives the
/// `$` doubling untouched, and [`substitute_install_dir`] turns it into the NSIS variable
/// afterwards.
const EXE_PLACEHOLDER: &str = "@PRVW_EXE@";

/// Where the installer puts `prvw.exe`, in NSIS's own spelling.
const INSTALLED_EXE: &str = r"$INSTDIR\prvw.exe";

/// The whole generated file, ready to compare with the committed one.
pub fn render() -> String {
    let writes = file_types::registration(Path::new(EXE_PLACEHOLDER));
    let removals = file_types::removal();

    let mut out = String::new();
    out.push_str(HEADER);
    out.push_str("\n!macro PrvwRegisterFileTypes\n");
    for write in &writes {
        out.push_str(&write_line(write));
    }
    out.push_str("!macroend\n");
    out.push_str("\n!macro PrvwUnregisterFileTypes\n");
    for removal in &removals {
        out.push_str(&removal_line(removal));
    }
    out.push_str("!macroend\n");
    substitute_install_dir(&out)
}

/// The comment block at the top, which is what a reader who lands in the generated file sees.
const HEADER: &str = "\
; Prvw's file-type registration, for the installer and its uninstaller.
;
; GENERATED by `cargo xtask installer-registry` from `settings::windows::file_types`. Don't edit
; it by hand: `./scripts/check.sh --check installer` rewrites it and fails in CI when the two
; disagree. Add a format to `decoding::dispatch` and it appears here.
;
; Every key is under HKCU, so the installer needs no elevation, and nothing here touches
; `UserChoice`: since Windows 10 20H2 only the user can pick a default handler. What these keys
; buy is a place in Explorer's \"Open with\" list and a page of Prvw's own in Settings.
";

/// One `WriteRegStr`. An unnamed value is `\"\"`, which is how NSIS spells a key's default.
fn write_line(value: &RegistryValue) -> String {
    format!(
        "  WriteRegStr HKCU {} {} {}\n",
        nsis_string(&value.key),
        nsis_string(value.name.as_deref().unwrap_or("")),
        nsis_string(&value.value),
    )
}

/// One deletion. `/ifempty` is what keeps a shared extension key that another viewer also
/// registered in.
fn removal_line(removal: &RegistryRemoval) -> String {
    match removal {
        RegistryRemoval::KeyTree(key) => {
            format!("  DeleteRegKey HKCU {}\n", nsis_string(key))
        }
        RegistryRemoval::KeyIfEmpty(key) => {
            format!("  DeleteRegKey /ifempty HKCU {}\n", nsis_string(key))
        }
        RegistryRemoval::Value { key, name } => format!(
            "  DeleteRegValue HKCU {} {}\n",
            nsis_string(key),
            nsis_string(name)
        ),
    }
}

/// Quote a string for NSIS: double every `$`, then wrap it in a delimiter it doesn't contain.
///
/// Panics if a value manages to contain all three delimiters, which would mean no legal spelling
/// exists. Nothing in the registration comes close, and a silent mis-quote would be worse.
fn nsis_string(value: &str) -> String {
    let escaped = value.replace('$', "$$");
    let delimiter = ['"', '\'', '`']
        .into_iter()
        .find(|quote| !escaped.contains(*quote))
        .unwrap_or_else(|| panic!("{value:?} contains every NSIS string delimiter"));
    format!("{delimiter}{escaped}{delimiter}")
}

/// Turn the placeholder back into the NSIS variable, after the `$` doubling is done with.
fn substitute_install_dir(rendered: &str) -> String {
    rendered.replace(EXE_PLACEHOLDER, INSTALLED_EXE)
}

#[cfg(test)]
mod tests {
    use super::*;

    /// The generated file is what the installer compiles, so a broken string would show up as a
    /// makensis error rather than a wrong registry key. These check the shapes that matter.
    #[test]
    fn the_command_line_keeps_its_quotes() {
        let rendered = render();
        assert!(
            rendered.contains(r#"'"$INSTDIR\prvw.exe" "%1"'"#),
            "the open command lost its quoting:\n{rendered}"
        );
    }

    #[test]
    fn a_dollar_that_isnt_ours_is_escaped() {
        assert_eq!(nsis_string("100$"), r#""100$$""#);
        assert_eq!(nsis_string(r#"say "hi""#), r#"'say "hi"'"#);
        assert_eq!(nsis_string("it's"), r#""it's""#);
        assert_eq!(nsis_string(r#"both " and '"#), "`both \" and '`");
    }

    /// `$INSTDIR` has to reach the installer as a variable, not as the literal `$$INSTDIR` the
    /// escaping would otherwise produce.
    #[test]
    fn the_install_dir_stays_a_variable() {
        let rendered = render();
        assert!(rendered.contains(r"$INSTDIR\prvw.exe"));
        assert!(!rendered.contains("$$INSTDIR"));
        assert!(!rendered.contains(EXE_PLACEHOLDER));
    }

    /// Both macros exist and are balanced, which is the one thing a truncated generator would
    /// break without makensis being around to notice.
    #[test]
    fn both_macros_open_and_close() {
        let rendered = render();
        assert_eq!(rendered.matches("!macro ").count(), 2);
        assert_eq!(rendered.matches("!macroend").count(), 2);
        assert!(rendered.contains("!macro PrvwRegisterFileTypes"));
        assert!(rendered.contains("!macro PrvwUnregisterFileTypes"));
    }

    /// Every format the decoder opens reaches the installer. This is the whole reason the file
    /// is generated rather than written by hand.
    #[test]
    fn every_decodable_format_reaches_the_installer() {
        let rendered = render();
        for extension in file_types::extensions() {
            assert!(
                rendered.contains(&format!(r"Software\Classes\{extension}\OpenWithProgids")),
                "{extension} never reaches the installer"
            );
        }
        assert!(rendered.contains(".cr3"));
        assert!(!rendered.contains(".txt"));
    }

    /// Nothing the installer writes needs elevation, and nothing it writes is Windows'. Only the
    /// instructions count: the header explains `UserChoice` at length, and prose isn't a write.
    #[test]
    fn the_installer_stays_out_of_hklm_and_user_choice() {
        for line in render().lines() {
            let line = line.trim();
            if line.is_empty() || line.starts_with(';') {
                continue;
            }
            let lowered = line.to_lowercase();
            assert!(!lowered.contains("hklm"), "{line} needs elevation");
            assert!(
                !lowered.contains("userchoice"),
                "{line} touches UserChoice, which Windows owns"
            );
        }
    }
}
